version: '3'
services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa55w0rd2019"
    ports:
      - "1433:1433"

  ecommerceapi:
    image: marisouzas2/ecommerce_madenn:latest
    container_name: ecommerce_madenn
    ports:
      - "5000:80"
    depends_on:
      - db

  ecommercebff:
    image: marisouzas2/ecommerce_bff:latest
    container_name: ecommerce_bff
    ports:
      - "8000:80"
    depends_on:
      - ecommerceapi