version: '3'
services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa55w0rd2019"
    ports:
      - "1433:1433"

  ec-users:
    image: marisouzas2/ecommerce_users:latest
    container_name: ec-users
    ports:
      - "9000:80"
    depends_on:
      - db
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db,1433;Database=ecommerce-database;trusted_connection=false;User Id=sa;Password=Pa55w0rd2019;Persist Security Info=False;Encrypt=False"

  ecommerceapi:
    image: marisouzas2/ecommerce_madenn:latest
    container_name: ecommerce_madenn
    ports:
      - "5000:80"
    depends_on:
      - db
      - ec-users
    environment:
      - "ASPNETCORE_DOCKER=1"

  ec-bff:
    image: marisouzas2/ecommerce_bff:latest
    container_name: ec-bff
    ports:
      - "8000:80"
    depends_on:
      - ecommerceapi
      - ec-users
    environment:
      - "Urls:UserApi=http://ec-users:80"
      - "Urls:EcommerceApi=http://ecommerceapi:80"
   
  ec-front:
    image: dennerlucio/ecommerce_front:latest
    container_name: ec-front
    ports:
      - "8080:8080"
    depends_on:
      - ec-bff
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local