version: '3'
services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa55w0rd2019"
    ports:
      - "1433:1433"

  ecommerceapi:
    image: marisouzas2/ecommerce_madenn:latest
    container_name: ecommerce_madenn
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - "ASPNETCORE_DOCKER=1"
      - "ConnectionStrings__DefaultConnection=Server=db,1433;Database=ecommerce-database;trusted_connection=false;User Id=sa;Password=Pa55w0rd2019;Persist Security Info=False;Encrypt=False"

  ec-users:
    image: marisouzas2/ecommerce_users:latest
    container_name: ec-users
    ports:
      - "9000:80"
    depends_on:
      - db
    environment:
      - "ASPNETCORE_DOCKER=1"
      - "ConnectionStrings__DefaultConnection=Server=db,1433;Database=ecommerce-users;trusted_connection=false;User Id=sa;Password=Pa55w0rd2019;Persist Security Info=False;Encrypt=False"

  ec-bff:
    image: marisouzas2/ecommerce_bff:latest
    container_name: ec-bff
    ports:
      - "8000:80"
    depends_on:
      - ecommerceapi
      - ec-users
    environment:
      - "Urls:UserApi=http://ec-users:80"
      - "Urls:EcommerceApi=http://ecommerceapi:80"
   
  ec-front:
    image: dennerlucio/ecommerce_front:latest
    container_name: ec-front
    ports:
      - "8080:8080"
    depends_on:
      - ec-bff
    