version: '3'
services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa55w0rd2019"
    ports:
      - "1444:1433"

  mq:
    image: rabbitmq:3-management
    ports:
       - 15672:15672

  ecommerceapi:
    image: ecommerce_madenn
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
      - mq